import mongoose from "mongoose";

const FincheckPushSubscriptionSchema = new mongoose.Schema(
  {
    empId: { type: String, required: true, index: true },
    // The subscription object generated by the browser
    endpoint: { type: String, required: true },
    keys: {
      p256dh: { type: String, required: true },
      auth: { type: String, required: true }
    },
    // User Agent to distinguish devices (Mobile vs Desktop)
    userAgent: { type: String },
    createdAt: { type: Date, default: Date.now }
  },
  {
    collection: "fincheck_push_subscriptions"
  }
);

// Ensure unique subscriptions per device/endpoint
FincheckPushSubscriptionSchema.index({ endpoint: 1 }, { unique: true });

export default (connection) =>
  connection.model("FincheckPushSubscription", FincheckPushSubscriptionSchema);
