import React, { useRef } from "react";
import { QRCodeCanvas } from "qrcode.react";
import {
  Download,
  QrCode,
  Calendar,
  FileText,
  User,
  Layers,
  Hash
} from "lucide-react";

const YPivotQAInspectionQRCode = ({
  reportId,
  inspectionDate,
  orderNos,
  reportType,
  inspectionType,
  empId
}) => {
  const qrRef = useRef(null);

  // --- Helper to format data ---
  const formattedDate = inspectionDate
    ? new Date(inspectionDate).toLocaleDateString()
    : "N/A";

  const formattedOrders = Array.isArray(orderNos)
    ? orderNos.join(", ")
    : orderNos || "N/A";

  // --- DOWNLOAD HANDLER (High Quality Image Generation) ---
  const handleDownload = () => {
    // 1. Get the source QR image from the DOM
    const sourceCanvas = qrRef.current.querySelector("canvas");
    if (!sourceCanvas) return;
    const qrImageURI = sourceCanvas.toDataURL("image/png");

    // 2. Create a High-Resolution Canvas for the final image
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");

    // High Resolution Dimensions (e.g., 1200px width)
    const width = 1200;
    const height = 1600;

    canvas.width = width;
    canvas.height = height;

    // 3. Draw Background
    ctx.fillStyle = "#FFFFFF";
    ctx.fillRect(0, 0, width, height);

    // 4. Draw Header Background
    ctx.fillStyle = "#4F46E5"; // Indigo-600
    ctx.fillRect(0, 0, width, 250);

    // 5. Draw Title (White text on Indigo)
    ctx.textAlign = "center";
    ctx.fillStyle = "#FFFFFF";

    ctx.font = "bold 60px sans-serif";
    ctx.fillText("FIN CHECK INSPECTION", width / 2, 120);

    ctx.font = "40px sans-serif";
    ctx.fillText("QUALITY REPORT", width / 2, 190);

    // 6. Draw Report ID (Big and Bold)
    ctx.fillStyle = "#111827"; // Dark Gray
    ctx.font = "bold 100px monospace";
    ctx.fillText(reportId, width / 2, 400);

    ctx.font = "30px sans-serif";
    ctx.fillStyle = "#9CA3AF"; // Light Gray
    ctx.fillText("REPORT ID", width / 2, 450);

    // 7. Load QR Image and Draw it
    const img = new Image();
    img.onload = () => {
      // Draw QR in the center
      const qrSize = 500;
      ctx.drawImage(img, (width - qrSize) / 2, 500, qrSize, qrSize);

      // --- Draw Data Table Section ---
      const startY = 1100;
      const startX = 150;
      const rowHeight = 80;
      const labelWidth = 300;

      ctx.textAlign = "left";

      const drawRow = (label, value, y) => {
        // Label
        ctx.font = "bold 40px sans-serif";
        ctx.fillStyle = "#6B7280"; // Gray-500
        ctx.fillText(label, startX, y);

        // Value
        ctx.font = "bold 40px sans-serif";
        ctx.fillStyle = "#1F2937"; // Gray-800
        ctx.fillText(value, startX + labelWidth, y);

        // Underline
        ctx.beginPath();
        ctx.moveTo(startX, y + 20);
        ctx.lineTo(width - startX, y + 20);
        ctx.strokeStyle = "#E5E7EB";
        ctx.lineWidth = 2;
        ctx.stroke();
      };

      drawRow("Date:", formattedDate, startY);
      drawRow("Inspector:", empId, startY + rowHeight);
      drawRow("Insp. Type:", inspectionType, startY + rowHeight * 2);
      drawRow("Report:", reportType, startY + rowHeight * 3);

      // Handle potentially long Order string
      const orderLabelY = startY + rowHeight * 4;
      ctx.font = "bold 40px sans-serif";
      ctx.fillStyle = "#6B7280";
      ctx.fillText("Order(s):", startX, orderLabelY);

      ctx.font = "bold 40px sans-serif";
      ctx.fillStyle = "#4F46E5"; // Indigo for Order

      // Simple truncation if too long for one line, or wrap (simplified here to truncate with ellipsis)
      let orderText = formattedOrders;
      const maxOrderWidth = width - (startX + labelWidth) - 100;
      if (ctx.measureText(orderText).width > maxOrderWidth) {
        // Crude truncation for canvas
        while (
          ctx.measureText(orderText + "...").width > maxOrderWidth &&
          orderText.length > 0
        ) {
          orderText = orderText.slice(0, -1);
        }
        orderText += "...";
      }
      ctx.fillText(orderText, startX + labelWidth, orderLabelY);

      // 8. Footer
      ctx.textAlign = "center";
      ctx.font = "italic 30px sans-serif";
      ctx.fillStyle = "#9CA3AF";
      ctx.fillText("Generated by YQMS System", width / 2, height - 50);

      // 9. Trigger Download
      const pngUrl = canvas.toDataURL("image/png");
      const downloadLink = document.createElement("a");
      downloadLink.href = pngUrl;
      downloadLink.download = `Inspection_${reportId}.png`;
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);
    };

    img.src = qrImageURI;
  };

  if (!reportId) return null;

  return (
    <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 p-4 mb-6 flex flex-col sm:flex-row items-center gap-5 animate-fadeIn">
      {/* 1. Visible QR Code (DOM Element used for generation) */}
      <div
        ref={qrRef}
        className="bg-white p-2 rounded-xl border border-gray-100 shadow-sm flex-shrink-0"
      >
        {/* We keep this size moderate for UI display, but scale it up during download generation */}
        <QRCodeCanvas
          value={String(reportId)}
          size={120}
          level={"H"}
          includeMargin={true}
        />
      </div>

      {/* 2. Visible Meta Data (UI only) */}
      <div className="flex-1 min-w-0 text-center sm:text-left space-y-2">
        <div>
          <h3 className="text-lg font-black text-gray-800 dark:text-white flex items-center justify-center sm:justify-start gap-2">
            <QrCode className="w-5 h-5 text-indigo-500" />
            <span className="font-mono tracking-wider">{reportId}</span>
          </h3>
          <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest">
            Official Report ID
          </p>
        </div>

        <div className="grid grid-cols-2 gap-x-6 gap-y-1 text-[10px] text-gray-600 dark:text-gray-300">
          <div className="flex items-center gap-1.5 truncate">
            <Calendar className="w-3 h-3 text-gray-400" />
            <span className="font-bold text-gray-500">Date:</span>{" "}
            {formattedDate}
          </div>
          <div className="flex items-center gap-1.5 truncate">
            <User className="w-3 h-3 text-gray-400" />
            <span className="font-bold text-gray-500">QA ID:</span> {empId}
          </div>
          <div className="flex items-center gap-1.5 truncate">
            <Layers className="w-3 h-3 text-gray-400" />
            <span className="font-bold text-gray-500">Type:</span>{" "}
            {inspectionType}
          </div>
          <div className="flex items-center gap-1.5 truncate">
            <FileText className="w-3 h-3 text-gray-400" />
            <span className="font-bold text-gray-500">Report:</span>{" "}
            {reportType}
          </div>
          <div className="col-span-2 flex items-center gap-1.5 truncate border-t border-gray-100 dark:border-gray-700 pt-1 mt-1">
            <Hash className="w-3 h-3 text-gray-400" />
            <span className="font-bold text-gray-500">Order:</span>
            <span
              className="text-indigo-600 dark:text-indigo-400 font-medium"
              title={formattedOrders}
            >
              {formattedOrders}
            </span>
          </div>
        </div>
      </div>

      {/* 3. Download Action */}
      <button
        onClick={handleDownload}
        className="flex-shrink-0 flex items-center gap-2 px-4 py-2 bg-gray-900 dark:bg-gray-700 hover:bg-gray-800 dark:hover:bg-gray-600 text-white rounded-lg font-bold text-xs transition-all shadow-md active:scale-95"
      >
        <Download className="w-3.5 h-3.5" />
        Save QR
      </button>
    </div>
  );
};

export default YPivotQAInspectionQRCode;
